### ISSUE TITLE
Sinon integration needed?

### ISSUE THREAD

**Issue by christian-bromann** [michaelguild13/Selenium-WebdriverIO-Mocha-Chai-Sinon-Boilerplate#1]
Why did you integrate Sinon? I don't see that it is being used at all and it doesn't seem to be the right fit for e2e testing for me.

**Comment by michaelguild13** [comment]
It's just there so you can do whatever you want with it. It's a boilerplate :)

**Comment by michaelguild13** [comment]
The boilerplate has been updated and tested. I'll cut sinon out.
