### ISSUE TITLE
Timed out waiting for driver server to start when using PhanomJS

### ISSUE THREAD

**Issue by ThreadedLemon** [michaelguild13/Selenium-WebdriverIO-Mocha-Chai-Sinon-Boilerplate#5]
I am receiving a timeout error after cloning the repo and running the following:

`npm install`
`npm test`

Error:

`[14:28:38]  COMMAND     POST     "/wd/hub/session"`
`[14:28:38]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"phantomjs","logging
Prefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}}}`
`ERROR: Timed out waiting for driver server to start.
Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
System info: host: '_[ommitted]_', ip: '_[ommitted]_', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown`
`phantomjs`
`Error: Timed out waiting for driver server to start.
Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
System info: host: '_[ommitted]_', ip: '_[ommitted]_', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown`

Everything works as expected if I change the browser within `wdio.conf.js` to `chrome` or `firefox`

Additional Info:
node: 6.3.1
npm: 3.10.8

**Comment by michaelguild13** [comment]
I'll check it out sometime this week. Are you sure your selenium server is running and installed correctly?

**Comment by ThreadedLemon** [comment]
@michaelguild13 yes `selenium-standalone` has been installed and is running.

**Comment by michaelguild13** [comment]
Sorry for the delay. From what I can tell, it seems as though phantomjs is no longer supported

**Comment by michaelguild13** [comment]
I will be updating this boilerplate to no longer use phantom in favor of the chromedriver.

**Comment by michaelguild13** [comment]
The boilerplate has been updated and tested
